load("@rules_cc//cc:cc_binary.bzl", "cc_binary")

cc_binary(
  name = "random_polygon",
  srcs = ["random_polygon.cc"],
  deps = [
    "//core:core",
  ],
)

cc_binary(
  name = "triangulate",
  srcs = ["triangulate.cc"],
  deps = [
    "//core:core",
  ],
)
